"""orderd_items column add

Revision ID: 67842bcd3f98
Revises: 62fd3d73596b
Create Date: 2024-08-31 00:50:25.233691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '67842bcd3f98'
down_revision: Union[str, None] = '62fd3d73596b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkout', sa.Column('order_items', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checkout', 'order_items')